#pragma once

#include <stdint.h>
#include <stddef.h>

#define CTA_NUM_LEDS    (511)

typedef enum {
    RED_LINE,
    BLUE_LINE,
    GREEN_LINE,
    BROWN_LINE,
    PURPLE_LINE,
    YELLOW_LINE,
    PINK_LINE,
    ORANGE_LINE,

    LINE_COUNT
} __attribute__((__packed__)) line_name_t;

typedef enum {
    FLAG_RED_LINE    = 1 << RED_LINE,
    FLAG_BLUE_LINE   = 1 << BLUE_LINE,
    FLAG_GREEN_LINE  = 1 << GREEN_LINE,
    FLAG_BROWN_LINE  = 1 << BROWN_LINE,
    FLAG_PURPLE_LINE = 1 << PURPLE_LINE,
    FLAG_YELLOW_LINE = 1 << YELLOW_LINE,
    FLAG_PINK_LINE   = 1 << PINK_LINE,
    FLAG_ORANGE_LINE = 1 << ORANGE_LINE,
} __attribute__((__packed__)) line_flag_t;

typedef enum {
    _18TH_PINK                                                         = 40830,
    _35TH_ARCHER_ORANGE                                                = 40120,
    _35TH_BRONZEVILLE_IIT_GREEN                                        = 41120,
    _43RD_GREEN                                                        = 41270,
    _47TH_GREEN                                                        = 41080,
    _47TH_RED                                                          = 41230,
    _51ST_GREEN                                                        = 40130,
    _54TH_CERMAK_PINK                                                  = 40580,
    _63RD_RED                                                          = 40910,
    _69TH_RED                                                          = 40990,
    _79TH_RED                                                          = 40240,
    _87TH_RED                                                          = 41430,
    _95TH_DAN_RYAN_RED                                                 = 40450,
    ADAMS_WABASH_BROWN_GREEN_ORANGE_PINK_PURPLE                        = 40680,
    ADDISON_RED                                                        = 41420,
    ADDISON_BROWN                                                      = 41440,
    ADDISON_BLUE                                                       = 41240,
    ARGYLE_RED                                                         = 41200,
    ARMITAGE_BROWN_PURPLE                                              = 40660,
    ASHLAND_GREEN_PINK                                                 = 40170,
    ASHLAND_ORANGE                                                     = 41060,
    ASHLAND_63RD_GREEN                                                 = 40290,
    AUSTIN_BLUE                                                        = 40010,
    AUSTIN_GREEN                                                       = 41260,
    BELMONT_BLUE                                                       = 40060,
    BELMONT_RED_BROWN_PURPLE                                           = 41320,
    BERWYN_RED                                                         = 40340,
    BRYN_MAWR_RED                                                      = 41380,
    CALIFORNIA_GREEN                                                   = 41360,
    CALIFORNIA_BLUE                                                    = 40570,
    CALIFORNIA_PINK                                                    = 40440,
    CENTRAL_GREEN                                                      = 40280,
    CENTRAL_PURPLE                                                     = 41250,
    CENTRAL_PARK_PINK                                                  = 40780,
    CERMAK_CHINATOWN_RED                                               = 41000,
    CERMAK_MCCORMICK_PLACE_GREEN                                       = 41690,
    CHICAGO_RED                                                        = 41450,
    CHICAGO_BROWN_PURPLE                                               = 40710,
    CHICAGO_BLUE                                                       = 41410,
    CICERO_BLUE                                                        = 40970,
    CICERO_GREEN                                                       = 40480,
    CICERO_PINK                                                        = 40420,
    CLARK_DIVISION_RED                                                 = 40630,
    CLARK_LAKE_BLUE_BROWN_GREEN_ORANGE_PURPLE_PINK                     = 40380,
    CLINTON_GREEN_PINK                                                 = 41160,
    CLINTON_BLUE                                                       = 40430,
    CONSERVATORY_GREEN                                                 = 41670,
    COTTAGE_GROVE_GREEN                                                = 40720,
    CUMBERLAND_BLUE                                                    = 40230,
    DAMEN_BLUE                                                         = 40590,
    DAMEN_GREEN                                                        = 41710,
    DAMEN_PINK                                                         = 40210,
    DAMEN_BROWN                                                        = 40090,
    DAVIS_PURPLE                                                       = 40050,
    DEMPSTER_PURPLE                                                    = 40690,
    DEMPSTER_SKOKIE_YELLOW                                             = 40140,
    DIVERSEY_BROWN_PURPLE                                              = 40530,
    DIVISION_BLUE                                                      = 40320,
    FOREST_PARK_BLUE                                                   = 40390,
    FOSTER_PURPLE                                                      = 40520,
    FRANCISCO_BROWN                                                    = 40870,
    FULLERTON_RED_BROWN_PURPLE                                         = 41220,
    GARFIELD_RED                                                       = 41170,
    GARFIELD_GREEN                                                     = 40510,
    GRAND_RED                                                          = 40330,
    GRAND_BLUE                                                         = 40490,
    GRANVILLE_RED                                                      = 40760,
    HALSTED_GREEN                                                      = 40940,
    HALSTED_ORANGE                                                     = 41130,
    HARLEM_BLUE_FOREST_PARK_BRANCH                                     = 40980,
    HARLEM_BLUE_OHARE_BRANCH                                           = 40750,
    HARLEM_LAKE_GREEN                                                  = 40020,
    HAROLD_WASHINGTON_LIBRARY_STATE_VAN_BUREN_BROWN_ORANGE_PURPLE_PINK = 40850,
    HARRISON_RED                                                       = 41490,
    HOWARD_RED_PURPLE_YELLOW                                           = 40900,
    ILLINOIS_MEDICAL_DISTRICT_BLUE                                     = 40810,
    INDIANA_GREEN                                                      = 40300,
    IRVING_PARK_BLUE                                                   = 40550,
    IRVING_PARK_BROWN                                                  = 41460,
    JACKSON_BLUE                                                       = 40070,
    JACKSON_RED                                                        = 40560,
    JARVIS_RED                                                         = 41190,
    JEFFERSON_PARK_BLUE                                                = 41280,
    KEDZIE_ORANGE                                                      = 41150,
    KEDZIE_GREEN                                                       = 41070,
    KEDZIE_PINK                                                        = 41040,
    KEDZIE_BROWN                                                       = 41180,
    KEDZIE_HOMAN_BLUE                                                  = 40250,
    KIMBALL_BROWN                                                      = 41290,
    KING_DRIVE_GREEN                                                   = 41140,
    KOSTNER_PINK                                                       = 40600,
    LAKE_RED                                                           = 41660,
    LARAMIE_GREEN                                                      = 40700,
    LASALLE_BLUE                                                       = 41340,
    LASALLE_VAN_BUREN_BROWN_ORANGE_PURPLE_PINK                         = 40160,
    LAWRENCE_RED                                                       = 40770,
    LINDEN_PURPLE                                                      = 41050,
    LOGAN_SQUARE_BLUE                                                  = 41020,
    LOYOLA_RED                                                         = 41300,
    MAIN_PURPLE                                                        = 40270,
    MERCHANDISE_MART_BROWN_PURPLE                                      = 40460,
    MIDWAY_ORANGE                                                      = 40930,
    MONROE_RED                                                         = 41090,
    MONROE_BLUE                                                        = 40790,
    MONTROSE_BLUE                                                      = 41330,
    MONTROSE_BROWN                                                     = 41500,
    MORGAN_GREEN_PINK                                                  = 41510,
    MORSE_RED                                                          = 40100,
    NORTH_CLYBOURN_RED                                                 = 40650,
    NOYES_PURPLE                                                       = 40400,
    OAK_PARK_GREEN                                                     = 41350,
    OAK_PARK_BLUE                                                      = 40180,
    OAKTON_SKOKIE_YELLOW                                               = 41680,
    OHARE_BLUE                                                         = 40890,
    PAULINA_BROWN                                                      = 41310,
    POLK_PINK                                                          = 41030,
    PULASKI_GREEN                                                      = 40030,
    PULASKI_BLUE                                                       = 40920,
    PULASKI_PINK                                                       = 40150,
    PULASKI_ORANGE                                                     = 40960,
    QUINCY_WELLS_BROWN_ORANGE_PURPLE_PINK                              = 40040,
    RACINE_BLUE                                                        = 40470,
    RIDGELAND_GREEN                                                    = 40610,
    ROCKWELL_BROWN                                                     = 41010,
    ROOSEVELT_RED_ORANGE_GREEN                                         = 41400,
    ROSEMONT_BLUE                                                      = 40820,
    SEDGWICK_BROWN_PURPLE                                              = 40800,
    SHERIDAN_RED                                                       = 40080,
    SOUTH_BOULEVARD_PURPLE                                             = 40840,
    SOUTHPORT_BROWN                                                    = 40360,
    SOX_35TH_RED                                                       = 40190,
    STATE_LAKE_BROWN_GREEN_ORANGE_PINK_PURPLE                          = 40260,
    THORNDALE_RED                                                      = 40880,
    UIC_HALSTED_BLUE                                                   = 40350,
    WASHINGTON_BLUE                                                    = 40370,
    WASHINGTON_WABASH_BROWN_GREEN_ORANGE_PURPLE_PINK                   = 41700,
    WASHINGTON_WELLS_BROWN_ORANGE_PURPLE_PINK                          = 40730,
    WELLINGTON_BROWN_PURPLE                                            = 41210,
    WESTERN_BROWN                                                      = 41480,
    WESTERN_BLUE_OHARE_BRANCH                                          = 40670,
    WESTERN_BLUE_FOREST_PARK_BRANCH                                    = 40220,
    WESTERN_ORANGE                                                     = 40310,
    WESTERN_PINK                                                       = 40740,
    WILSON_RED_PURPLE                                                  = 40540,
} __attribute__((__packed__)) station_id_t;

typedef enum {
    _18TH_54TH_CERMAK_BOUND                   = 30162,
    _18TH_LOOP_BOUND                          = 30161,
    _35TH_ARCHER_LOOP_BOUND                   = 30022,
    _35TH_ARCHER_MIDWAY_BOUND                 = 30023,
    _35_BRONZEVILLE_IIT_HARLEM_BOUND          = 30213,
    _35_BRONZEVILLE_IIT_63RD_BOUND            = 30214,
    _43RD_HARLEM_BOUND                        = 30245,
    _43RD_63RD_BOUND                          = 30246,
    _47TH_63RD_BOUND                          = 30210,
    _47TH_HOWARD_BOUND                        = 30237,
    _47TH_95TH_BOUND                          = 30238,
    _47TH_HARLEM_BOUND                        = 30209,
    _51ST_63RD_BOUND                          = 30025,
    _51ST_HARLEM_BOUND                        = 30024,
    _54TH_CERMAK_TERMINAL_ARRIVAL             = 30114,
    _54TH_CERMAK_LOOP_BOUND                   = 30113,
    _63RD_HOWARD_BOUND                        = 30177,
    _63RD_95TH_BOUND                          = 30178,
    _69TH_HOWARD_BOUND                        = 30191,
    _69TH_95TH_BOUND                          = 30192,
    _79TH_95TH_BOUND                          = 30047,
    _79TH_HOWARD_BOUND                        = 30046,
    _87TH_HOWARD_BOUND                        = 30275,
    _87TH_95TH_BOUND                          = 30276,
    _95TH_DAN_RYAN_HOWARD_BOUND               = 30088,
    _95TH_DAN_RYAN_95TH_BOUND                 = 30089,
    ADAMS_WABASH_OUTER_LOOP                   = 30131,
    ADAMS_WABASH_INNER_LOOP                   = 30132,
    ADDISON_95TH_BOUND                        = 30274,
    ADDISON_LOOP_BOUND                        = 30278,
    ADDISON_OHARE_BOUND                       = 30239,
    ADDISON_KIMBALL_BOUND                     = 30277,
    ADDISON_FOREST_PK_BOUND                   = 30240,
    ADDISON_HOWARD_BOUND                      = 30273,
    ARGYLE_95TH_BOUND                         = 30230,
    ARGYLE_HOWARD_BOUND                       = 30229,
    ARMITAGE_KIMBALL_LINDEN_BOUND             = 30127,
    ARMITAGE_LOOP_BOUND                       = 30128,
    ASHLAND_HARLEM_54TH_CERMAK_BOUND          = 30033,
    ASHLAND_LOOP_63RD_BOUND                   = 30032,
    ASHLAND_MIDWAY_BOUND                      = 30206,
    ASHLAND_LOOP_BOUND                        = 30205,
    ASHLAND_63RD_TERMINAL_ARRIVAL             = 30057,
    ASHLAND_63RD_HARLEM_BOUND                 = 30056,
    AUSTIN_FOREST_PK_BOUND                    = 30002,
    AUSTIN_OHARE_BOUND                        = 30001,
    AUSTIN_63RD_BOUND                         = 30243,
    AUSTIN_HARLEM_BOUND                       = 30244,
    BELMONT_OHARE_BRANCH_OHARE_BOUND          = 30012,
    BELMONT_LOOP_BOUND                        = 30258,
    BELMONT_OHARE_BRANCH_FOREST_PK_BOUND      = 30013,
    BELMONT_95TH_BOUND                        = 30256,
    BELMONT_HOWARD_BOUND                      = 30255,
    BELMONT_KIMBALL_LINDEN_BOUND              = 30257,
    BERWYN_95TH_BOUND                         = 30067,
    BERWYN_HOWARD_BOUND                       = 30066,
    BRYN_MAWR_95TH_BOUND                      = 30268,
    BRYN_MAWR_HOWARD_BOUND                    = 30267,
    CALIFORNIA_HARLEM_BOUND                   = 30266,
    CALIFORNIA_OHARE_BOUND                    = 30111,
    CALIFORNIA_63RD_BOUND                     = 30265,
    CALIFORNIA_54TH_CERMAK_BOUND              = 30087,
    CALIFORNIA_FOREST_PK_BOUND                = 30112,
    CALIFORNIA_LOOP_BOUND                     = 30086,
    CENTRAL_63RD_BOUND                        = 30054,
    CENTRAL_HARLEM_BOUND                      = 30055,
    CENTRAL_LINDEN_BOUND                      = 30241,
    CENTRAL_HOWARD_LOOP_BOUND                 = 30242,
    CENTRAL_PARK_54TH_CERMAK_BOUND            = 30152,
    CENTRAL_PARK_LOOP_BOUND                   = 30151,
    CERMAK_CHINATOWN_HOWARD_BOUND             = 30193,
    CERMAK_CHINATOWN_95TH_BOUND               = 30194,
    CERMAK_MCCORMICK_PLACE_63RD_BOUND         = 30382,
    CERMAK_MCCORMICK_PLACE_HARLEM_BOUND       = 30381,
    CHICAGO_95TH_BOUND                        = 30280,
    CHICAGO_LOOP_BOUND                        = 30138,
    CHICAGO_FOREST_PK_BOUND                   = 30272,
    CHICAGO_OHARE_BOUND                       = 30271,
    CHICAGO_HOWARD_BOUND                      = 30279,
    CHICAGO_KIMBALL_LINDEN_BOUND              = 30137,
    CICERO_OHARE_BOUND                        = 30187,
    CICERO_63RD_BOUND                         = 30094,
    CICERO_FOREST_PK_BOUND                    = 30188,
    CICERO_LOOP_BOUND                         = 30082,
    CICERO_54TH_CERMAK_BOUND                  = 30083,
    CICERO_HARLEM_BOUND                       = 30009,
    CLARK_DIVISION_HOWARD_BOUND               = 30121,
    CLARK_DIVISION_95TH_BOUND                 = 30122,
    CLARK_LAKE_OUTER_LOOP                     = 30075,
    CLARK_LAKE_FOREST_PK_BOUND                = 30374,
    CLARK_LAKE_OHARE_BOUND                    = 30375,
    CLARK_LAKE_INNER_LOOP                     = 30074,
    CLINTON_LOOP_63RD_BOUND                   = 30221,
    CLINTON_FOREST_PK_BOUND                   = 30085,
    CLINTON_OHARE_BOUND                       = 30084,
    CLINTON_HARLEM_54TH_CERMAK_BOUND          = 30222,
    CONSERVATORY_63RD_BOUND                   = 30291,
    CONSERVATORY_HARLEM_BOUND                 = 30292,
    COTTAGE_GROVE_HARLEM_BOUND                = 30140,
    COTTAGE_GROVE_TERMINAL_ARRIVAL            = 30139,
    CUMBERLAND_OHARE_BOUND                    = 30044,
    CUMBERLAND_FOREST_PK_BOUND                = 30045,
    DAMEN_MILWAUKEE_OHARE_BOUND               = 30115,
    DAMEN_63RD_BOUND                          = 30387,
    DAMEN_HARLEM_BOUND                        = 30388,
    DAMEN_54TH_CERMAK_BOUND                   = 30041,
    DAMEN_BROWN_LOOP_BOUND                    = 30019,
    DAMEN_MILWAUKEE_FOREST_PK_BOUND           = 30116,
    DAMEN_PINK_LOOP_BOUND                     = 30040,
    DAMEN_KIMBALL_BOUND                       = 30018,
    DAVIS_LINDEN_BOUND                        = 30010,
    DAVIS_HOWARD_LOOP_BOUND                   = 30011,
    DEMPSTER_LINDEN_BOUND                     = 30133,
    DEMPSTER_HOWARD_LOOP_BOUND                = 30134,
    DEMPSTER_SKOKIE_HOWARD_BOUND              = 30027,
    DEMPSTER_SKOKIE_ARRIVAL                   = 30026,
    DIVERSEY_LOOP_BOUND                       = 30104,
    DIVERSEY_KIMBALL_LINDEN_BOUND             = 30103,
    DIVISION_OHARE_BOUND                      = 30062,
    DIVISION_FOREST_PK_BOUND                  = 30063,
    FOREST_PARK_TERMINAL_ARRIVAL              = 30077,
    FOREST_PARK_OHARE_BOUND                   = 30076,
    FOSTER_LINDEN_BOUND                       = 30101,
    FOSTER_HOWARD_LOOP_BOUND                  = 30102,
    FRANCISCO_LOOP_BOUND                      = 30168,
    FRANCISCO_KIMBALL_BOUND                   = 30167,
    FULLERTON_KIMBALL_LINDEN_BOUND            = 30235,
    FULLERTON_HOWARD_BOUND                    = 30233,
    FULLERTON_LOOP_BOUND                      = 30236,
    FULLERTON_95TH_BOUND                      = 30234,
    GARFIELD_95TH_BOUND                       = 30224,
    GARFIELD_HOWARD_BOUND                     = 30223,
    GARFIELD_63RD_BOUND                       = 30100,
    GARFIELD_HARLEM_BOUND                     = 30099,
    GRAND_STATE_95TH_BOUND                    = 30065,
    GRAND_MILWAUKEE_FOREST_PK_BOUND           = 30096,
    GRAND_MILWAUKEE_OHARE_BOUND               = 30095,
    GRAND_STATE_HOWARD_BOUND                  = 30064,
    GRANVILLE_95TH_BOUND                      = 30148,
    GRANVILLE_HOWARD_BOUND                    = 30147,
    HALSTED_63RD_ASHLAND_BOUND                = 30184,
    HALSTED_63RD_HARLEM_BOUND                 = 30183,
    HALSTED_MIDWAY_BOUND                      = 30216,
    HALSTED_LOOP_BOUND                        = 30215,
    HARLEM_FOREST_PK_BRANCH_TERMINAL_ARRIVAL  = 30190,
    HARLEM_OHARE_BRANCH_OHARE_BOUND           = 30145,
    HARLEM_OHARE_BRANCH_FOREST_PK_BOUND       = 30146,
    HARLEM_FOREST_PK_BRANCH_OHARE_BOUND       = 30189,
    HARLEM_TERMINAL_ARRIVAL                   = 30004,
    HARLEM_63RD_BOUND                         = 30003,
    HW_LIBRARY_OUTER_LOOP                     = 30165,
    HW_LIBRARY_INNER_LOOP                     = 30166,
    HARRISON_95TH_BOUND                       = 30286,
    HARRISON_HOWARD_BOUND                     = 30285,
    HOWARD_95TH_BOUND                         = 30174,
    HOWARD_LINDEN_SKOKIE_BOUND                = 30175,
    HOWARD_RED_TERMINAL_ARRIVAL               = 30173,
    HOWARD_PURPLE_YELLOW_TERMINAL_ARRIVAL     = 30176,
    ILLINOIS_MEDICAL_DISTRICT_FOREST_PK_BOUND = 30158,
    ILLINOIS_MEDICAL_DISTRICT_OHARE_BOUND     = 30157,
    INDIANA_HARLEM_BOUND                      = 30058,
    INDIANA_63RD_BOUND                        = 30059,
    IRVING_PARK_OHARE_BRANCH_OHARE_BOUND      = 30107,
    IRVING_PARK_KIMBALL_BOUND                 = 30281,
    IRVING_PARK_LOOP_BOUND                    = 30282,
    IRVING_PARK_OHARE_BRANCH_FOREST_PK_BOUND  = 30108,
    JACKSON_DEARBORN_OHARE_BOUND              = 30014,
    JACKSON_STATE_HOWARD_BOUND                = 30109,
    JACKSON_STATE_95TH_BOUND                  = 30110,
    JACKSON_DEARBORN_FOREST_PK_BOUND          = 30015,
    JARVIS_95TH_BOUND                         = 30228,
    JARVIS_HOWARD_BOUND                       = 30227,
    JEFFERSON_PARK_OHARE_BOUND                = 30247,
    JEFFERSON_PARK_FOREST_PK_BOUND            = 30248,
    KEDZIE_ORANGE_LOOP_BOUND                  = 30219,
    KEDZIE_63RD_BOUND                         = 30207,
    KEDZIE_HARLEM_BOUND                       = 30208,
    KEDZIE_MIDWAY_BOUND                       = 30220,
    KEDZIE_54TH_CERMAK_BOUND                  = 30202,
    KEDZIE_PINK_LOOP_BOUND                    = 30201,
    KEDZIE_KIMBALL_BOUND                      = 30225,
    KEDZIE_BROWN_LOOP_BOUND                   = 30226,
    KEDZIE_HOMAN_OHARE_BOUND                  = 30048,
    KEDZIE_HOMAN_FOREST_PK_BOUND              = 30049,
    KIMBALL_LOOP_BOUND                        = 30250,
    KIMBALL_TERMINAL_ARRIVAL                  = 30249,
    KING_DRIVE_COTTAGE_GROVE_BOUND            = 30217,
    KING_DRIVE_HARLEM_BOUND                   = 30218,
    KOSTNER_LOOP_BOUND                        = 30117,
    KOSTNER_54TH_CERMAK_BOUND                 = 30118,
    LAKE_95TH_BOUND                           = 30290,
    LAKE_HOWARD_BOUND                         = 30289,
    LARAMIE_HARLEM_BOUND                      = 30136,
    LARAMIE_63RD_BOUND                        = 30135,
    LASALLE_OHARE_BOUND                       = 30261,
    LASALLE_FOREST_PK_BOUND                   = 30262,
    LASALLE_VAN_BUREN_OUTER_LOOP              = 30030,
    LASALLE_VAN_BUREN_INNER_LOOP              = 30031,
    LAWRENCE_95TH_BOUND                       = 30150,
    LAWRENCE_HOWARD_BOUND                     = 30149,
    LINDEN_LINDEN_BOUND                       = 30203,
    LINDEN_HOWARD_LOOP_BOUND                  = 30204,
    LOGAN_SQUARE_FOREST_PK_BOUND              = 30198,
    LOGAN_SQUARE_OHARE_BOUND                  = 30197,
    LOYOLA_HOWARD_BOUND                       = 30251,
    LOYOLA_95TH_BOUND                         = 30252,
    MAIN_LINDEN_BOUND                         = 30052,
    MAIN_HOWARD_LOOP_BOUND                    = 30053,
    MERCHANDISE_MART_KIMBALL_LINDEN_BOUND     = 30090,
    MERCHANDISE_MART_LOOP_BOUND               = 30091,
    MIDWAY_ARRIVAL                            = 30182,
    MIDWAY_LOOP_BOUND                         = 30181,
    MONROE_95TH_BOUND                         = 30212,
    MONROE_HOWARD_BOUND                       = 30211,
    MONROE_FOREST_PK_BOUND                    = 30154,
    MONROE_OHARE_BOUND                        = 30153,
    MONTROSE_OHARE_BOUND                      = 30259,
    MONTROSE_KIMBALL_BOUND                    = 30287,
    MONTROSE_LOOP_BOUND                       = 30288,
    MONTROSE_FOREST_PK_BOUND                  = 30260,
    MORGAN_HARLEM_54TH_CERMAK_BOUND           = 30296,
    MORGAN_LOOP_63RD_BOUND                    = 30295,
    MORSE_HOWARD_BOUND                        = 30020,
    MORSE_95TH_BOUND                          = 30021,
    NORTH_CLYBOURN_95TH_BOUND                 = 30126,
    NORTH_CLYBOURN_HOWARD_BOUND               = 30125,
    NOYES_HOWARD_LOOP_BOUND                   = 30079,
    NOYES_LINDEN_BOUND                        = 30078,
    OAK_PARK_63RD_BOUND                       = 30263,
    OAK_PARK_OHARE_BOUND                      = 30034,
    OAK_PARK_FOREST_PK_BOUND                  = 30035,
    OAK_PARK_HARLEM_BOUND                     = 30264,
    OAKTON_SKOKIE_DEMPSTER_SKOKIE_BOUND       = 30297,
    OAKTON_SKOKIE_HOWARD_BOUND                = 30298,
    OHARE_FOREST_PK_BOUND                     = 30172,
    OHARE_TERMINAL_ARRIVAL                    = 30171,
    PAULINA_LOOP_BOUND                        = 30254,
    PAULINA_KIMBALL_BOUND                     = 30253,
    POLK_LOOP_BOUND                           = 30199,
    POLK_54TH_CERMAK_BOUND                    = 30200,
    PULASKI_HARLEM_BOUND                      = 30006,
    PULASKI_FOREST_PK_BOUND                   = 30180,
    PULASKI_PINK_LOOP_BOUND                   = 30028,
    PULASKI_MIDWAY_BOUND                      = 30186,
    PULASKI_OHARE_BOUND                       = 30179,
    PULASKI_ORANGE_LOOP_BOUND                 = 30185,
    PULASKI_63RD_BOUND                        = 30005,
    PULASKI_54TH_CERMAK_BOUND                 = 30029,
    QUINCY_WELLS_INNER_LOOP                   = 30007,
    QUINCY_WELLS_OUTER_LOOP                   = 30008,
    RACINE_OHARE_BOUND                        = 30092,
    RACINE_FOREST_PK_BOUND                    = 30093,
    RIDGELAND_HARLEM_BOUND                    = 30120,
    RIDGELAND_63RD_BOUND                      = 30119,
    ROCKWELL_LOOP_BOUND                       = 30196,
    ROCKWELL_KIMBALL_BOUND                    = 30195,
    ROOSEVELT_HOWARD_BOUND                    = 30269,
    ROOSEVELT_MIDWAY_63RD_BOUND               = 30081,
    ROOSEVELT_LOOP_HARLEM_BOUND               = 30080,
    ROOSEVELT_95TH_BOUND                      = 30270,
    ROSEMONT_FOREST_PK_BOUND                  = 30160,
    ROSEMONT_OHARE_BOUND                      = 30159,
    SEDGWICK_LOOP_BOUND                       = 30156,
    SEDGWICK_KIMBALL_LINDEN_BOUND             = 30155,
    SHERIDAN_95TH_BOUND                       = 30017,
    SHERIDAN_LOOP_BOUND                       = 30294,
    SHERIDAN_HOWARD_BOUND                     = 30016,
    SHERIDAN_HOWARD_LINDEN_BOUND              = 30293,
    SOUTH_BLVD_HOWARD_LOOP_BOUND              = 30164,
    SOUTH_BLVD_LINDEN_BOUND                   = 30163,
    SOUTHPORT_LOOP_BOUND                      = 30071,
    SOUTHPORT_KIMBALL_BOUND                   = 30070,
    SOX_35TH_HOWARD_BOUND                     = 30036,
    SOX_35TH_95TH_BOUND                       = 30037,
    STATE_LAKE_INNER_LOOP                     = 30050,
    STATE_LAKE_OUTER_LOOP                     = 30051,
    THORNDALE_HOWARD_BOUND                    = 30169,
    THORNDALE_95TH_BOUND                      = 30170,
    UIC_HALSTED_OHARE_BOUND                   = 30068,
    UIC_HALSTED_FOREST_PK_BOUND               = 30069,
    WASHINGTON_FOREST_PK_BOUND                = 30073,
    WASHINGTON_OHARE_BOUND                    = 30072,
    WASHINGTON_WABASH_INNER_LOOP              = 30384,
    WASHINGTON_WABASH_OUTER_LOOP              = 30383,
    WASHINGTON_WELLS_OUTER_LOOP               = 30142,
    WASHINGTON_WELLS_INNER_LOOP               = 30141,
    WELLINGTON_LOOP_BOUND                     = 30232,
    WELLINGTON_KIMBALL_LINDEN_BOUND           = 30231,
    WESTERN_BROWN_LOOP_BOUND                  = 30284,
    WESTERN_OHARE_BRANCH_OHARE_BOUND          = 30129,
    WESTERN_FOREST_PK_BRANCH_OHARE_BOUND      = 30042,
    WESTERN_MIDWAY_BOUND                      = 30061,
    WESTERN_54TH_CERMAK_BOUND                 = 30144,
    WESTERN_FOREST_PK_BRANCH_FOREST_PK_BOUND  = 30043,
    WESTERN_ORANGE_LOOP_BOUND                 = 30060,
    WESTERN_OHARE_BRANCH_FOREST_PK_BOUND      = 30130,
    WESTERN_KIMBALL_BOUND                     = 30283,
    WESTERN_PINK_LOOP_BOUND                   = 30143,
    WILSON_LOOP_BOUND                         = 30385,
    WILSON_LINDEN_BOUND                       = 30386,
    WILSON_95TH_BOUND                         = 30106,
    WILSON_HOWARD_BOUND                       = 30105,
} stop_id_t;

typedef struct {
    float lat;
    float lon;
} location_t;

typedef struct {
    station_id_t id;
    location_t location;
    uint16_t led_index[LINE_COUNT];
} station_t;

typedef struct {
    uint16_t start;
    int8_t count;
} led_index_t;

typedef struct {
    led_index_t rail;
    uint16_t station;
} led_segment_t;

typedef struct stop {
    line_flag_t line;
    uint8_t station_idx;
    led_index_t led[LINE_COUNT];
} stop_t;

const uint16_t* cta_get_leds_for_line(line_name_t line, size_t* count);
led_segment_t cta_get_leds(size_t stop_id, line_name_t line);
